apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-ucp-vsp-dc1-platinum
  annotations:
    kubernetes.io/description: Hitachi Storage Plug-in for Containers
provisioner: hspc.csi.hitachi.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  serialNumber: "715359"
  poolID: "0"
  portID: CL1-D,CL2-D
  connectionType: iscsi
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-publish-secret-name: "secret-dc1"
  csi.storage.k8s.io/node-publish-secret-namespace: "hspc-operator-system"
  csi.storage.k8s.io/provisioner-secret-name: "secret-dc1"
  csi.storage.k8s.io/provisioner-secret-namespace: "hspc-operator-system"
  csi.storage.k8s.io/controller-publish-secret-name: "secret-dc1"
  csi.storage.k8s.io/controller-publish-secret-namespace: "hspc-operator-system"
  csi.storage.k8s.io/node-stage-secret-name: "secret-dc1"
  csi.storage.k8s.io/node-stage-secret-namespace: "hspc-operator-system"
  csi.storage.k8s.io/controller-expand-secret-name: "secret-dc1"
  csi.storage.k8s.io/controller-expand-secret-namespace: "hspc-operator-system"